// Code generated by protoc-gen-go.
// source: monitorproto.proto
// DO NOT EDIT!

/*
Package monitorproto is a generated protocol buffer package.

It is generated from these files:
	monitorproto.proto

It has these top-level messages:
	Empty
	Heartbeat
	HeartbeatList
	MessageLog
	ValueLog
	LogWriteResponse
*/
package monitorproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import discovery "github.com/brotherlogic/discovery/proto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Heartbeat struct {
	// The entry
	Entry *discovery.RegistryEntry `protobuf:"bytes,1,opt,name=entry" json:"entry,omitempty"`
	// The time of the beat
	BeatTime int64 `protobuf:"varint,2,opt,name=beat_time,json=beatTime" json:"beat_time,omitempty"`
}

func (m *Heartbeat) Reset()                    { *m = Heartbeat{} }
func (m *Heartbeat) String() string            { return proto.CompactTextString(m) }
func (*Heartbeat) ProtoMessage()               {}
func (*Heartbeat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Heartbeat) GetEntry() *discovery.RegistryEntry {
	if m != nil {
		return m.Entry
	}
	return nil
}

type HeartbeatList struct {
	Beats []*Heartbeat `protobuf:"bytes,1,rep,name=beats" json:"beats,omitempty"`
}

func (m *HeartbeatList) Reset()                    { *m = HeartbeatList{} }
func (m *HeartbeatList) String() string            { return proto.CompactTextString(m) }
func (*HeartbeatList) ProtoMessage()               {}
func (*HeartbeatList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HeartbeatList) GetBeats() []*Heartbeat {
	if m != nil {
		return m.Beats
	}
	return nil
}

type MessageLog struct {
	// The entry writing the log
	Entry *discovery.RegistryEntry `protobuf:"bytes,1,opt,name=entry" json:"entry,omitempty"`
	// The message to be written to the logs
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *MessageLog) Reset()                    { *m = MessageLog{} }
func (m *MessageLog) String() string            { return proto.CompactTextString(m) }
func (*MessageLog) ProtoMessage()               {}
func (*MessageLog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MessageLog) GetEntry() *discovery.RegistryEntry {
	if m != nil {
		return m.Entry
	}
	return nil
}

type ValueLog struct {
	Entry *discovery.RegistryEntry `protobuf:"bytes,1,opt,name=entry" json:"entry,omitempty"`
	Value float32                  `protobuf:"fixed32,2,opt,name=value" json:"value,omitempty"`
}

func (m *ValueLog) Reset()                    { *m = ValueLog{} }
func (m *ValueLog) String() string            { return proto.CompactTextString(m) }
func (*ValueLog) ProtoMessage()               {}
func (*ValueLog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ValueLog) GetEntry() *discovery.RegistryEntry {
	if m != nil {
		return m.Entry
	}
	return nil
}

type LogWriteResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *LogWriteResponse) Reset()                    { *m = LogWriteResponse{} }
func (m *LogWriteResponse) String() string            { return proto.CompactTextString(m) }
func (*LogWriteResponse) ProtoMessage()               {}
func (*LogWriteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func init() {
	proto.RegisterType((*Empty)(nil), "monitorproto.Empty")
	proto.RegisterType((*Heartbeat)(nil), "monitorproto.Heartbeat")
	proto.RegisterType((*HeartbeatList)(nil), "monitorproto.HeartbeatList")
	proto.RegisterType((*MessageLog)(nil), "monitorproto.MessageLog")
	proto.RegisterType((*ValueLog)(nil), "monitorproto.ValueLog")
	proto.RegisterType((*LogWriteResponse)(nil), "monitorproto.LogWriteResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for MonitorService service

type MonitorServiceClient interface {
	ReceiveHeartbeat(ctx context.Context, in *discovery.RegistryEntry, opts ...grpc.CallOption) (*Heartbeat, error)
	GetHeartbeats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HeartbeatList, error)
	WriteMessageLog(ctx context.Context, in *MessageLog, opts ...grpc.CallOption) (*LogWriteResponse, error)
	WriteValueLog(ctx context.Context, in *ValueLog, opts ...grpc.CallOption) (*LogWriteResponse, error)
}

type monitorServiceClient struct {
	cc *grpc.ClientConn
}

func NewMonitorServiceClient(cc *grpc.ClientConn) MonitorServiceClient {
	return &monitorServiceClient{cc}
}

func (c *monitorServiceClient) ReceiveHeartbeat(ctx context.Context, in *discovery.RegistryEntry, opts ...grpc.CallOption) (*Heartbeat, error) {
	out := new(Heartbeat)
	err := grpc.Invoke(ctx, "/monitorproto.MonitorService/ReceiveHeartbeat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) GetHeartbeats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HeartbeatList, error) {
	out := new(HeartbeatList)
	err := grpc.Invoke(ctx, "/monitorproto.MonitorService/GetHeartbeats", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) WriteMessageLog(ctx context.Context, in *MessageLog, opts ...grpc.CallOption) (*LogWriteResponse, error) {
	out := new(LogWriteResponse)
	err := grpc.Invoke(ctx, "/monitorproto.MonitorService/WriteMessageLog", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) WriteValueLog(ctx context.Context, in *ValueLog, opts ...grpc.CallOption) (*LogWriteResponse, error) {
	out := new(LogWriteResponse)
	err := grpc.Invoke(ctx, "/monitorproto.MonitorService/WriteValueLog", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MonitorService service

type MonitorServiceServer interface {
	ReceiveHeartbeat(context.Context, *discovery.RegistryEntry) (*Heartbeat, error)
	GetHeartbeats(context.Context, *Empty) (*HeartbeatList, error)
	WriteMessageLog(context.Context, *MessageLog) (*LogWriteResponse, error)
	WriteValueLog(context.Context, *ValueLog) (*LogWriteResponse, error)
}

func RegisterMonitorServiceServer(s *grpc.Server, srv MonitorServiceServer) {
	s.RegisterService(&_MonitorService_serviceDesc, srv)
}

func _MonitorService_ReceiveHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(discovery.RegistryEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).ReceiveHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitorproto.MonitorService/ReceiveHeartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).ReceiveHeartbeat(ctx, req.(*discovery.RegistryEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_GetHeartbeats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).GetHeartbeats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitorproto.MonitorService/GetHeartbeats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).GetHeartbeats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_WriteMessageLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageLog)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).WriteMessageLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitorproto.MonitorService/WriteMessageLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).WriteMessageLog(ctx, req.(*MessageLog))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_WriteValueLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValueLog)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).WriteValueLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitorproto.MonitorService/WriteValueLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).WriteValueLog(ctx, req.(*ValueLog))
	}
	return interceptor(ctx, in, info, handler)
}

var _MonitorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "monitorproto.MonitorService",
	HandlerType: (*MonitorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveHeartbeat",
			Handler:    _MonitorService_ReceiveHeartbeat_Handler,
		},
		{
			MethodName: "GetHeartbeats",
			Handler:    _MonitorService_GetHeartbeats_Handler,
		},
		{
			MethodName: "WriteMessageLog",
			Handler:    _MonitorService_WriteMessageLog_Handler,
		},
		{
			MethodName: "WriteValueLog",
			Handler:    _MonitorService_WriteValueLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("monitorproto.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x91, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x6d, 0x4b, 0x6c, 0x3b, 0x5a, 0x2d, 0xab, 0x68, 0x48, 0x41, 0x24, 0x27, 0x0f, 0x9a,
	0x42, 0x3d, 0x78, 0xf3, 0x22, 0xa5, 0x0a, 0x2d, 0xc8, 0x2a, 0xd5, 0x9b, 0x24, 0x71, 0x48, 0x17,
	0x9a, 0x6e, 0xd9, 0xdd, 0x06, 0xfa, 0x66, 0x3e, 0x9e, 0xbb, 0x1b, 0x9a, 0x34, 0x42, 0x11, 0xbd,
	0x84, 0xcc, 0x37, 0xf3, 0xfd, 0x76, 0xfe, 0x00, 0x49, 0xf9, 0x82, 0x29, 0x2e, 0x96, 0x82, 0x2b,
	0x1e, 0xd8, 0x2f, 0x39, 0xdc, 0xd6, 0xbc, 0xbb, 0x84, 0xa9, 0xd9, 0x2a, 0x0a, 0x62, 0x9e, 0xf6,
	0x23, 0xad, 0xcc, 0x50, 0xcc, 0x79, 0xc2, 0xe2, 0xfe, 0x27, 0x93, 0x31, 0xcf, 0x50, 0xac, 0xfb,
	0xb6, 0xb0, 0x8c, 0x73, 0x8c, 0xdf, 0x04, 0x67, 0x98, 0x2e, 0xd5, 0xda, 0x7f, 0x87, 0xf6, 0x23,
	0x86, 0x42, 0x45, 0x18, 0x2a, 0x12, 0x80, 0x83, 0x0b, 0x25, 0xd6, 0x6e, 0xed, 0xb2, 0x76, 0x75,
	0x30, 0x70, 0x83, 0xd2, 0x46, 0x31, 0x61, 0x52, 0xa7, 0x86, 0x26, 0x4f, 0xf3, 0x32, 0xd2, 0x83,
	0xb6, 0xf1, 0x7d, 0x28, 0x96, 0xa2, 0x5b, 0xd7, 0x9e, 0x06, 0x6d, 0x19, 0xe1, 0x55, 0xc7, 0xfe,
	0x3d, 0x74, 0x0a, 0xf2, 0x58, 0x7b, 0xc9, 0x0d, 0x38, 0xe6, 0x5f, 0x6a, 0x7a, 0x43, 0xd3, 0xcf,
	0x83, 0xca, 0x78, 0x45, 0x2d, 0xcd, 0xab, 0xfc, 0x29, 0xc0, 0x04, 0xa5, 0x0c, 0x13, 0x1c, 0xf3,
	0xe4, 0xcf, 0xad, 0xb9, 0xd0, 0x4c, 0x73, 0xb7, 0x6d, 0xac, 0x4d, 0x37, 0xa1, 0xff, 0x0c, 0xad,
	0x69, 0x38, 0x5f, 0xfd, 0x8b, 0x7a, 0x0a, 0x4e, 0x66, 0xbc, 0x96, 0x59, 0xa7, 0x79, 0xe0, 0x5f,
	0x43, 0x57, 0xc3, 0xde, 0x04, 0x53, 0x48, 0x51, 0x2e, 0xf9, 0x42, 0xa2, 0x79, 0x5f, 0xae, 0xe2,
	0x58, 0xbf, 0x69, 0xd9, 0x2d, 0xba, 0x09, 0x07, 0x5f, 0x75, 0x38, 0x9a, 0xe4, 0x93, 0xbf, 0xa0,
	0xc8, 0x58, 0x8c, 0x64, 0x04, 0x5d, 0x8a, 0x31, 0xb2, 0x0c, 0xcb, 0x5b, 0xec, 0xec, 0xc5, 0xdb,
	0xb5, 0x38, 0x7f, 0x8f, 0x3c, 0x40, 0x67, 0x84, 0xaa, 0x50, 0x24, 0x39, 0xa9, 0xd6, 0xda, 0x9b,
	0x7b, 0xbd, 0x1d, 0x00, 0x73, 0x25, 0x0d, 0x99, 0xc0, 0xb1, 0x9d, 0x65, 0x6b, 0xfb, 0x6e, 0xd5,
	0x51, 0x66, 0xbc, 0x8b, 0x6a, 0xe6, 0xe7, 0x1e, 0x34, 0xee, 0x09, 0x3a, 0x56, 0x2a, 0x96, 0x7e,
	0x56, 0xb5, 0x6c, 0xf4, 0xdf, 0x51, 0xd1, 0xbe, 0xcd, 0xdc, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff,
	0xfe, 0xc5, 0xd4, 0xdf, 0x19, 0x03, 0x00, 0x00,
}
