// Code generated by protoc-gen-go. DO NOT EDIT.
// source: monitorproto.proto

/*
Package monitorproto is a generated protocol buffer package.

It is generated from these files:
	monitorproto.proto

It has these top-level messages:
	Empty
	Heartbeat
	HeartbeatList
	MessageLog
	ValueLog
	LogWriteResponse
	MessageLogReadResponse
	FunctionCall
	Stats
	StatsList
*/
package monitorproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import discovery "github.com/brotherlogic/discovery/proto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Heartbeat struct {
	// The entry
	Entry *discovery.RegistryEntry `protobuf:"bytes,1,opt,name=entry" json:"entry,omitempty"`
	// The time of the beat
	BeatTime int64 `protobuf:"varint,2,opt,name=beat_time,json=beatTime" json:"beat_time,omitempty"`
}

func (m *Heartbeat) Reset()                    { *m = Heartbeat{} }
func (m *Heartbeat) String() string            { return proto.CompactTextString(m) }
func (*Heartbeat) ProtoMessage()               {}
func (*Heartbeat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Heartbeat) GetEntry() *discovery.RegistryEntry {
	if m != nil {
		return m.Entry
	}
	return nil
}

func (m *Heartbeat) GetBeatTime() int64 {
	if m != nil {
		return m.BeatTime
	}
	return 0
}

type HeartbeatList struct {
	Beats []*Heartbeat `protobuf:"bytes,1,rep,name=beats" json:"beats,omitempty"`
}

func (m *HeartbeatList) Reset()                    { *m = HeartbeatList{} }
func (m *HeartbeatList) String() string            { return proto.CompactTextString(m) }
func (*HeartbeatList) ProtoMessage()               {}
func (*HeartbeatList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HeartbeatList) GetBeats() []*Heartbeat {
	if m != nil {
		return m.Beats
	}
	return nil
}

type MessageLog struct {
	// The entry writing the log
	Entry *discovery.RegistryEntry `protobuf:"bytes,1,opt,name=entry" json:"entry,omitempty"`
	// The message to be written to the logs
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	// The timestamp of the written log
	Timestamps int64 `protobuf:"varint,3,opt,name=timestamps" json:"timestamps,omitempty"`
}

func (m *MessageLog) Reset()                    { *m = MessageLog{} }
func (m *MessageLog) String() string            { return proto.CompactTextString(m) }
func (*MessageLog) ProtoMessage()               {}
func (*MessageLog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MessageLog) GetEntry() *discovery.RegistryEntry {
	if m != nil {
		return m.Entry
	}
	return nil
}

func (m *MessageLog) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *MessageLog) GetTimestamps() int64 {
	if m != nil {
		return m.Timestamps
	}
	return 0
}

type ValueLog struct {
	Entry *discovery.RegistryEntry `protobuf:"bytes,1,opt,name=entry" json:"entry,omitempty"`
	Value float32                  `protobuf:"fixed32,2,opt,name=value" json:"value,omitempty"`
}

func (m *ValueLog) Reset()                    { *m = ValueLog{} }
func (m *ValueLog) String() string            { return proto.CompactTextString(m) }
func (*ValueLog) ProtoMessage()               {}
func (*ValueLog) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ValueLog) GetEntry() *discovery.RegistryEntry {
	if m != nil {
		return m.Entry
	}
	return nil
}

func (m *ValueLog) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type LogWriteResponse struct {
	// Whether the log was written
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	// The timestamp at which the log was written
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *LogWriteResponse) Reset()                    { *m = LogWriteResponse{} }
func (m *LogWriteResponse) String() string            { return proto.CompactTextString(m) }
func (*LogWriteResponse) ProtoMessage()               {}
func (*LogWriteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *LogWriteResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *LogWriteResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type MessageLogReadResponse struct {
	// The response from the logs
	Logs []*MessageLog `protobuf:"bytes,1,rep,name=logs" json:"logs,omitempty"`
}

func (m *MessageLogReadResponse) Reset()                    { *m = MessageLogReadResponse{} }
func (m *MessageLogReadResponse) String() string            { return proto.CompactTextString(m) }
func (*MessageLogReadResponse) ProtoMessage()               {}
func (*MessageLogReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *MessageLogReadResponse) GetLogs() []*MessageLog {
	if m != nil {
		return m.Logs
	}
	return nil
}

type FunctionCall struct {
	Binary string `protobuf:"bytes,1,opt,name=binary" json:"binary,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Time   int32  `protobuf:"varint,3,opt,name=time" json:"time,omitempty"`
}

func (m *FunctionCall) Reset()                    { *m = FunctionCall{} }
func (m *FunctionCall) String() string            { return proto.CompactTextString(m) }
func (*FunctionCall) ProtoMessage()               {}
func (*FunctionCall) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *FunctionCall) GetBinary() string {
	if m != nil {
		return m.Binary
	}
	return ""
}

func (m *FunctionCall) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FunctionCall) GetTime() int32 {
	if m != nil {
		return m.Time
	}
	return 0
}

type Stats struct {
	Binary        string  `protobuf:"bytes,1,opt,name=binary" json:"binary,omitempty"`
	Name          string  `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	NumberOfCalls int32   `protobuf:"varint,3,opt,name=number_of_calls,json=numberOfCalls" json:"number_of_calls,omitempty"`
	MeanRunTime   int32   `protobuf:"varint,4,opt,name=mean_run_time,json=meanRunTime" json:"mean_run_time,omitempty"`
	RunTimes      []int32 `protobuf:"varint,5,rep,packed,name=run_times,json=runTimes" json:"run_times,omitempty"`
}

func (m *Stats) Reset()                    { *m = Stats{} }
func (m *Stats) String() string            { return proto.CompactTextString(m) }
func (*Stats) ProtoMessage()               {}
func (*Stats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Stats) GetBinary() string {
	if m != nil {
		return m.Binary
	}
	return ""
}

func (m *Stats) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Stats) GetNumberOfCalls() int32 {
	if m != nil {
		return m.NumberOfCalls
	}
	return 0
}

func (m *Stats) GetMeanRunTime() int32 {
	if m != nil {
		return m.MeanRunTime
	}
	return 0
}

func (m *Stats) GetRunTimes() []int32 {
	if m != nil {
		return m.RunTimes
	}
	return nil
}

type StatsList struct {
	Stats []*Stats `protobuf:"bytes,1,rep,name=stats" json:"stats,omitempty"`
}

func (m *StatsList) Reset()                    { *m = StatsList{} }
func (m *StatsList) String() string            { return proto.CompactTextString(m) }
func (*StatsList) ProtoMessage()               {}
func (*StatsList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *StatsList) GetStats() []*Stats {
	if m != nil {
		return m.Stats
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "monitorproto.Empty")
	proto.RegisterType((*Heartbeat)(nil), "monitorproto.Heartbeat")
	proto.RegisterType((*HeartbeatList)(nil), "monitorproto.HeartbeatList")
	proto.RegisterType((*MessageLog)(nil), "monitorproto.MessageLog")
	proto.RegisterType((*ValueLog)(nil), "monitorproto.ValueLog")
	proto.RegisterType((*LogWriteResponse)(nil), "monitorproto.LogWriteResponse")
	proto.RegisterType((*MessageLogReadResponse)(nil), "monitorproto.MessageLogReadResponse")
	proto.RegisterType((*FunctionCall)(nil), "monitorproto.FunctionCall")
	proto.RegisterType((*Stats)(nil), "monitorproto.Stats")
	proto.RegisterType((*StatsList)(nil), "monitorproto.StatsList")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MonitorService service

type MonitorServiceClient interface {
	ReceiveHeartbeat(ctx context.Context, in *discovery.RegistryEntry, opts ...grpc.CallOption) (*Heartbeat, error)
	GetHeartbeats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HeartbeatList, error)
	WriteMessageLog(ctx context.Context, in *MessageLog, opts ...grpc.CallOption) (*LogWriteResponse, error)
	WriteValueLog(ctx context.Context, in *ValueLog, opts ...grpc.CallOption) (*LogWriteResponse, error)
	ReadMessageLogs(ctx context.Context, in *discovery.RegistryEntry, opts ...grpc.CallOption) (*MessageLogReadResponse, error)
	WriteFunctionCall(ctx context.Context, in *FunctionCall, opts ...grpc.CallOption) (*Empty, error)
	GetStats(ctx context.Context, in *FunctionCall, opts ...grpc.CallOption) (*StatsList, error)
}

type monitorServiceClient struct {
	cc *grpc.ClientConn
}

func NewMonitorServiceClient(cc *grpc.ClientConn) MonitorServiceClient {
	return &monitorServiceClient{cc}
}

func (c *monitorServiceClient) ReceiveHeartbeat(ctx context.Context, in *discovery.RegistryEntry, opts ...grpc.CallOption) (*Heartbeat, error) {
	out := new(Heartbeat)
	err := grpc.Invoke(ctx, "/monitorproto.MonitorService/ReceiveHeartbeat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) GetHeartbeats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HeartbeatList, error) {
	out := new(HeartbeatList)
	err := grpc.Invoke(ctx, "/monitorproto.MonitorService/GetHeartbeats", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) WriteMessageLog(ctx context.Context, in *MessageLog, opts ...grpc.CallOption) (*LogWriteResponse, error) {
	out := new(LogWriteResponse)
	err := grpc.Invoke(ctx, "/monitorproto.MonitorService/WriteMessageLog", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) WriteValueLog(ctx context.Context, in *ValueLog, opts ...grpc.CallOption) (*LogWriteResponse, error) {
	out := new(LogWriteResponse)
	err := grpc.Invoke(ctx, "/monitorproto.MonitorService/WriteValueLog", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) ReadMessageLogs(ctx context.Context, in *discovery.RegistryEntry, opts ...grpc.CallOption) (*MessageLogReadResponse, error) {
	out := new(MessageLogReadResponse)
	err := grpc.Invoke(ctx, "/monitorproto.MonitorService/ReadMessageLogs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) WriteFunctionCall(ctx context.Context, in *FunctionCall, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/monitorproto.MonitorService/WriteFunctionCall", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorServiceClient) GetStats(ctx context.Context, in *FunctionCall, opts ...grpc.CallOption) (*StatsList, error) {
	out := new(StatsList)
	err := grpc.Invoke(ctx, "/monitorproto.MonitorService/GetStats", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MonitorService service

type MonitorServiceServer interface {
	ReceiveHeartbeat(context.Context, *discovery.RegistryEntry) (*Heartbeat, error)
	GetHeartbeats(context.Context, *Empty) (*HeartbeatList, error)
	WriteMessageLog(context.Context, *MessageLog) (*LogWriteResponse, error)
	WriteValueLog(context.Context, *ValueLog) (*LogWriteResponse, error)
	ReadMessageLogs(context.Context, *discovery.RegistryEntry) (*MessageLogReadResponse, error)
	WriteFunctionCall(context.Context, *FunctionCall) (*Empty, error)
	GetStats(context.Context, *FunctionCall) (*StatsList, error)
}

func RegisterMonitorServiceServer(s *grpc.Server, srv MonitorServiceServer) {
	s.RegisterService(&_MonitorService_serviceDesc, srv)
}

func _MonitorService_ReceiveHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(discovery.RegistryEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).ReceiveHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitorproto.MonitorService/ReceiveHeartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).ReceiveHeartbeat(ctx, req.(*discovery.RegistryEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_GetHeartbeats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).GetHeartbeats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitorproto.MonitorService/GetHeartbeats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).GetHeartbeats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_WriteMessageLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageLog)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).WriteMessageLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitorproto.MonitorService/WriteMessageLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).WriteMessageLog(ctx, req.(*MessageLog))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_WriteValueLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValueLog)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).WriteValueLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitorproto.MonitorService/WriteValueLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).WriteValueLog(ctx, req.(*ValueLog))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_ReadMessageLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(discovery.RegistryEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).ReadMessageLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitorproto.MonitorService/ReadMessageLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).ReadMessageLogs(ctx, req.(*discovery.RegistryEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_WriteFunctionCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FunctionCall)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).WriteFunctionCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitorproto.MonitorService/WriteFunctionCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).WriteFunctionCall(ctx, req.(*FunctionCall))
	}
	return interceptor(ctx, in, info, handler)
}

func _MonitorService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FunctionCall)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitorproto.MonitorService/GetStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServiceServer).GetStats(ctx, req.(*FunctionCall))
	}
	return interceptor(ctx, in, info, handler)
}

var _MonitorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "monitorproto.MonitorService",
	HandlerType: (*MonitorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveHeartbeat",
			Handler:    _MonitorService_ReceiveHeartbeat_Handler,
		},
		{
			MethodName: "GetHeartbeats",
			Handler:    _MonitorService_GetHeartbeats_Handler,
		},
		{
			MethodName: "WriteMessageLog",
			Handler:    _MonitorService_WriteMessageLog_Handler,
		},
		{
			MethodName: "WriteValueLog",
			Handler:    _MonitorService_WriteValueLog_Handler,
		},
		{
			MethodName: "ReadMessageLogs",
			Handler:    _MonitorService_ReadMessageLogs_Handler,
		},
		{
			MethodName: "WriteFunctionCall",
			Handler:    _MonitorService_WriteFunctionCall_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _MonitorService_GetStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "monitorproto.proto",
}

func init() { proto.RegisterFile("monitorproto.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 597 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0x5d, 0x6b, 0x13, 0x41,
	0x14, 0x4d, 0x9a, 0x6c, 0x9b, 0xdc, 0x36, 0xb6, 0x8e, 0xd2, 0x2e, 0xa9, 0x94, 0x30, 0x88, 0x44,
	0xd0, 0x14, 0x2a, 0xe8, 0x9b, 0x20, 0xa5, 0xad, 0x4a, 0xab, 0x32, 0x15, 0xf5, 0x2d, 0x4c, 0xb6,
	0xb7, 0xdb, 0x81, 0xdd, 0x9d, 0x30, 0x33, 0x1b, 0xc8, 0x3f, 0xf1, 0xc1, 0x1f, 0x2b, 0x33, 0x93,
	0xec, 0x47, 0x69, 0x8a, 0xf5, 0x65, 0x99, 0x7b, 0xee, 0xc7, 0x9c, 0x39, 0x7b, 0x2e, 0x90, 0x54,
	0x66, 0xc2, 0x48, 0x35, 0x55, 0xd2, 0xc8, 0x91, 0xfb, 0x92, 0xad, 0x2a, 0xd6, 0x7f, 0x17, 0x0b,
	0x73, 0x93, 0x4f, 0x46, 0x91, 0x4c, 0x0f, 0x27, 0x4a, 0x9a, 0x1b, 0x54, 0x89, 0x8c, 0x45, 0x74,
	0x78, 0x25, 0x74, 0x24, 0x67, 0xa8, 0xe6, 0x87, 0xae, 0xb0, 0x8c, 0xfd, 0x18, 0xba, 0x01, 0xc1,
	0x49, 0x3a, 0x35, 0x73, 0xfa, 0x0b, 0xba, 0x1f, 0x91, 0x2b, 0x33, 0x41, 0x6e, 0xc8, 0x08, 0x02,
	0xcc, 0x8c, 0x9a, 0x87, 0xcd, 0x41, 0x73, 0xb8, 0x79, 0x14, 0x8e, 0xca, 0x36, 0x86, 0xb1, 0xd0,
	0x46, 0xcd, 0x4f, 0x6c, 0x9e, 0xf9, 0x32, 0xb2, 0x0f, 0x5d, 0xdb, 0x37, 0x36, 0x22, 0xc5, 0x70,
	0x6d, 0xd0, 0x1c, 0xb6, 0x58, 0xc7, 0x02, 0xdf, 0x45, 0x8a, 0xf4, 0x3d, 0xf4, 0x8a, 0xc9, 0xe7,
	0x42, 0x1b, 0xf2, 0x1a, 0x02, 0x7b, 0xd6, 0x61, 0x73, 0xd0, 0x1a, 0x6e, 0x1e, 0xed, 0x8d, 0x6a,
	0xcf, 0x2b, 0x6a, 0x99, 0xaf, 0xa2, 0x33, 0x80, 0x0b, 0xd4, 0x9a, 0xc7, 0x78, 0x2e, 0xe3, 0x07,
	0x53, 0x0b, 0x61, 0x23, 0xf5, 0xdd, 0x8e, 0x58, 0x97, 0x2d, 0x43, 0x72, 0x00, 0x60, 0xf9, 0x6a,
	0xc3, 0xd3, 0xa9, 0x0e, 0x5b, 0x8e, 0x75, 0x05, 0xa1, 0xdf, 0xa0, 0xf3, 0x83, 0x27, 0xf9, 0x7f,
	0xdd, 0xfa, 0x14, 0x82, 0x99, 0xed, 0x75, 0x77, 0xae, 0x31, 0x1f, 0xd0, 0xcf, 0xb0, 0x73, 0x2e,
	0xe3, 0x9f, 0x4a, 0x18, 0x64, 0xa8, 0xa7, 0x32, 0xd3, 0x68, 0xf9, 0xe9, 0x3c, 0x8a, 0x50, 0x6b,
	0x37, 0xbb, 0xc3, 0x96, 0x21, 0x79, 0x06, 0xdd, 0x82, 0xcd, 0x42, 0xd4, 0x12, 0xa0, 0xa7, 0xb0,
	0x5b, 0xaa, 0xc2, 0x90, 0x5f, 0x15, 0x13, 0x5f, 0x41, 0x3b, 0x91, 0xf1, 0x52, 0xdd, 0xb0, 0xae,
	0x6e, 0xa5, 0xc7, 0x55, 0xd1, 0x2f, 0xb0, 0x75, 0x9a, 0x67, 0x91, 0x11, 0x32, 0x3b, 0xe6, 0x49,
	0x42, 0x76, 0x61, 0x7d, 0x22, 0x32, 0xbe, 0x78, 0x6a, 0x97, 0x2d, 0x22, 0x42, 0xa0, 0x9d, 0xf1,
	0x74, 0x29, 0xa2, 0x3b, 0x5b, 0xcc, 0xfd, 0x71, 0xab, 0x5d, 0xc0, 0xdc, 0x99, 0xfe, 0x69, 0x42,
	0x70, 0x69, 0xb8, 0xd1, 0x0f, 0x9a, 0xf4, 0x02, 0xb6, 0xb3, 0x3c, 0x9d, 0xa0, 0x1a, 0xcb, 0xeb,
	0x71, 0xc4, 0x93, 0x44, 0x2f, 0x86, 0xf6, 0x3c, 0xfc, 0xf5, 0xda, 0x92, 0xd3, 0x84, 0x42, 0x2f,
	0x45, 0x9e, 0x8d, 0x55, 0x9e, 0x79, 0xb3, 0xb5, 0x5d, 0xd5, 0xa6, 0x05, 0x59, 0x9e, 0x59, 0xbf,
	0x59, 0x33, 0x2e, 0xd3, 0x3a, 0x0c, 0x06, 0xad, 0x61, 0xc0, 0x3a, 0xca, 0xe7, 0x34, 0x7d, 0x0b,
	0x5d, 0xc7, 0xce, 0x19, 0xf1, 0x25, 0x04, 0xda, 0x94, 0x46, 0x7c, 0x52, 0x97, 0xca, 0xd5, 0x31,
	0x5f, 0x71, 0xf4, 0xbb, 0x0d, 0x8f, 0x2e, 0x7c, 0xf6, 0x12, 0xd5, 0x4c, 0x44, 0x48, 0xce, 0x60,
	0x87, 0x61, 0x84, 0x62, 0x86, 0xe5, 0xe2, 0xac, 0x34, 0x46, 0x7f, 0x95, 0xcb, 0x69, 0x83, 0x1c,
	0x43, 0xef, 0x0c, 0x4d, 0x81, 0x68, 0x72, 0x8b, 0x88, 0x5b, 0xd0, 0xfe, 0xfe, 0x8a, 0x01, 0xf6,
	0x25, 0xb4, 0x41, 0x2e, 0x60, 0xdb, 0x19, 0xab, 0xb2, 0x2a, 0x2b, 0x7f, 0x7d, 0xff, 0xa0, 0x9e,
	0xb9, 0x6d, 0x4a, 0xda, 0x20, 0x9f, 0xa0, 0xe7, 0xa0, 0x62, 0x03, 0x76, 0xeb, 0x2d, 0x4b, 0xfc,
	0x1f, 0x46, 0x5d, 0xc2, 0xb6, 0xf5, 0x67, 0x79, 0xbd, 0xbe, 0x47, 0xa6, 0xe7, 0x2b, 0xed, 0x5a,
	0xb1, 0x38, 0x6d, 0x90, 0x53, 0x78, 0xec, 0xee, 0xa9, 0x79, 0xb7, 0x5f, 0x6f, 0xae, 0xe6, 0xfa,
	0x77, 0x69, 0x4a, 0x1b, 0xe4, 0x03, 0x74, 0xce, 0xd0, 0x78, 0xc3, 0xde, 0xd7, 0xbe, 0x77, 0x87,
	0x37, 0xbc, 0xf2, 0x93, 0x75, 0x07, 0xbd, 0xf9, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x62, 0x29, 0xfb,
	0xb6, 0xa6, 0x05, 0x00, 0x00,
}
